import { Theme } from "theme.slint";
import { TabButton } from "widgets.slint";

export component BottomNavigation inherits VerticalLayout {
    // استقبال خصائص من الملف الرئيسي
    in property <bool> is-narrow;
    in-out property <int> current-tab;

    Rectangle { height: 1px; background: Theme.border; }
    
    Rectangle {
        background: Theme.surface;
        width: 100%;
        height: 65px;
        
        HorizontalLayout {
            width: 100%;
            height: 100%;
            alignment: center; // يجعل المحتوى في المنتصف إذا كانت الشاشة عريضة جداً
            
            // الحاوية التفاعلية الذكية
            Rectangle {
                width: 100%;
                max-width: 500px; // لن تتمدد الأزرار أكثر من 500 بكسل في شاشات الكمبيوتر
                
                HorizontalLayout {
                    padding-left: 16px;
                    padding-right: 16px;
                    padding-top: 10px;
                    padding-bottom: 10px;
                    spacing: 16px; // مسافة محترمة وثابتة آمنة من الحلقات
                    
                    TabButton { text: "حول"; active: root.current-tab == 2; clicked => { root.current-tab = 2; } horizontal-stretch: 1; }
                    TabButton { text: "الإعدادات"; active: root.current-tab == 1; clicked => { root.current-tab = 1; } horizontal-stretch: 1; }
                    TabButton { text: "الرئيسية"; active: root.current-tab == 0; clicked => { root.current-tab = 0; } horizontal-stretch: 1; }
                }
            }
        }
    }

    // المنطقة الآمنة للقائمة السفلية لحماية الأزرار من شريط إيماءات النظام
    Rectangle {
        height: root.is-narrow ? 24px : 0px; 
        background: Theme.surface;
    }
}